# Generated by Django 5.0.3 on 2024-05-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
